server:
  port: 8088

spring:
  #  datasource:
  #    driver-class-name:
  #    username:
  #    password:
  #    url:
  #    type:
  ai:
    openai:
      base-url: https://openai.qiniu.com
      api-key: sk-cf7b0ee9493a412b3017ff29324363de403ba5d5fe2199383085d90434952c94
      chat:
        options:
          model: gpt-oss-120b
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

